version: '3'
services:

  nosql-mongo:
    image: mongo
    ports:
      - "27018:27017"
    container_name: nosql-mongo
    volumes:
      - ./db/:/data/db


  server:
    image: server
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: server-digitic
    restart: always
    depends_on:
      - "nosql-mongo"
    volumes:
      - .:/app/
      - /app/server/node_modules
    env_file:
      - ./server/.env
    expose:
      - 8001

  nginx-proxy:
    image: reverse-proxy
    container_name: nginx-digitic
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - "80:80"
    depends_on:
      - "server"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/package.json:/usr/src/app/package.json
      - /var/log/nginx:/var/log/nginx

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch-digitic
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data



  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: logstash
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh  # Đặt múi giờ của hệ thống
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch


volumes:
  esdata:
    driver: local
  graylog_data:
    driver: local
  graylog_journal:
    driver: local
  
